services:
  # Servicio principal de React
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: /usr/local/bin/init.sh